#!/usr/bin/env bash
#Bash script that will display information about subdomains

subbdomain () 
{
    out=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ') 
    echo "$2 $out" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
    for i in "www" "lb-01" "web-01" "web-02"
    do
        subbdomain "$1" "$i"
    done
else
    subbdomain "$1" "$2"
fi