#!/usr/bin/env bash
# Bash script that will display information about subdomains.
subbdomain () {
    out=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ') 
    echo "$2 $out" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
for i in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$i" == "$2" ] ;
    then
	subbdomain "$1" "$i"
    fi
done
