#!/usr/bin/env bash
# install nginx

apt-get -y update
apt-get -y install nginx
sudo chown -R $ubuntu:$ubuntu /var/www
sudo echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart