#!/usr/bin/env bash
# Displays "Holberton School" 10 times
# Displays "Holberton School" and then Hi on a new line.
i=0
while [ $i -lt 10 ]
do echo "Holberton School"
	if [ $((i+1)) -eq 9 ]
	then
		echo "Hi"
		fi
        ((i++))
done